# ref: https://www.chezmoi.io/reference/configuration-file/variables/

progress = true # show progress bar
sourceDir = "~/tech/github.com/alewkinr/dotfiles" # source directory
persistentState = "~/tech/github.com/alewkinr/dotfiles/chezmoistate.boltdb" # persistent state directory

[data]
    # common
    name = "Ramil Aleshkin"
    email = "alewkinr@gmail.com"

    # github_token_secret_id secret id for github token in password manager
    github_token_secret_id = "z4glrciti5q2xasnxoni7ggemm"
    github_user = "alewkinr"

    # ssh_personal_key_secret_id secret id for my personal ssh key in password manager
    ssh_personal_key_secret_id = "hpppilgphqd7i5cr62dm24xozm"
    ssh_mts_key_secret_id = "hzpw4263i4burz66id7ewqzoy4"
    ssh_twigai_key_secret_id = "3scedmnxwx6wqtdnqrq5qxavka"

    # awscli_twig_ai_* variables for twig.ai aws profile
    awscli_twig_ai_profile_name = "twig.ai"
    awscli_twig_ai_region = "us-east-1"
    awscli_twig_ai_credentials_secret_id = "v2kfdsl7yarul7b2bumvqjukcq"

    # docher_hub_secret_id secret id for docker hub credentials in password manager
    docher_hub_secret_id = "3dfm6oav5sv2kjnj27p3xfvtju"